//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18047
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace What_day_is_it {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("What_day_is_it.LogResources", typeof(LogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Closed in tray.
        /// </summary>
        internal static string applicationClosed {
            get {
                return ResourceManager.GetString("applicationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Closed in tray to exit.
        /// </summary>
        internal static string applicationExit {
            get {
                return ResourceManager.GetString("applicationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New application is launched.
        /// </summary>
        internal static string applicationLaunch {
            get {
                return ResourceManager.GetString("applicationLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opened from tray.
        /// </summary>
        internal static string applicationOpened {
            get {
                return ResourceManager.GetString("applicationOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bad arguments:.
        /// </summary>
        internal static string badArguments {
            get {
                return ResourceManager.GetString("badArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Today is too big date.
        /// </summary>
        internal static string bigDate {
            get {
                return ResourceManager.GetString("bigDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data file was not found.
        /// </summary>
        internal static string dataNotFound {
            get {
                return ResourceManager.GetString("dataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bad input in data file: input date is after today.
        /// </summary>
        internal static string FileDateError {
            get {
                return ResourceManager.GetString("FileDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bad input in data file (exists):.
        /// </summary>
        internal static string FileExistsError {
            get {
                return ResourceManager.GetString("FileExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bad input in settings file (notifications): .
        /// </summary>
        internal static string FileNotificationsError {
            get {
                return ResourceManager.GetString("FileNotificationsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bad input in data file (sex): .
        /// </summary>
        internal static string FileSexError {
            get {
                return ResourceManager.GetString("FileSexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bad input in settings file (startUp): .
        /// </summary>
        internal static string FileStartUpError {
            get {
                return ResourceManager.GetString("FileStartUpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bad input in data file (year): .
        /// </summary>
        internal static string FileYearError {
            get {
                return ResourceManager.GetString("FileYearError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First Start window opened.
        /// </summary>
        internal static string firstSettingsOpened {
            get {
                return ResourceManager.GetString("firstSettingsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log in.
        /// </summary>
        internal static string logIn {
            get {
                return ResourceManager.GetString("logIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log in tray.
        /// </summary>
        internal static string logInTray {
            get {
                return ResourceManager.GetString("logInTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log in tray aborted -- it is disabled.
        /// </summary>
        internal static string logInTrayAborted {
            get {
                return ResourceManager.GetString("logInTrayAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log out.
        /// </summary>
        internal static string logOut {
            get {
                return ResourceManager.GetString("logOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving settings.
        /// </summary>
        internal static string saveSettings {
            get {
                return ResourceManager.GetString("saveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings file was not found.
        /// </summary>
        internal static string settingsNotFound {
            get {
                return ResourceManager.GetString("settingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings opened.
        /// </summary>
        internal static string settingsOpened {
            get {
                return ResourceManager.GetString("settingsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  .
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IO: .
        /// </summary>
        internal static string stringIO {
            get {
                return ResourceManager.GetString("stringIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на startup.
        /// </summary>
        internal static string stringStartUp {
            get {
                return ResourceManager.GetString("stringStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tried to log in again.
        /// </summary>
        internal static string tryLogAgain {
            get {
                return ResourceManager.GetString("tryLogAgain", resourceCulture);
            }
        }
    }
}
